### ISSUE TITLE
Bug: AFK kick messages when your team is out of respawns

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#10]
1. Be in a team that has no more respawns available.
2. Wait for 2-3 minutes.
3. Notice messages `"Move around or you will be kicked in 60 seconds."` and `"You were kicked for being AFK too long."` in chat. You will not actually be kicked, though.

Since your team can't spawn you, you doing nothing on the spectator screen is inconsequential.

**Comment by NoahTheLegend** [comment]
Will remove kickafk for spectators
