### ISSUE TITLE
Kick for running from vote after bad delta

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#105]
At end of match, I did some shenanigans.
Someone started a kickvote on me for griefing (lol)
The next match started and there was a bad delta error.
I got kicked with the reason being "ran from vote".
I didn't disconnect; I got disconnected by the game having a bug.

**Comment by NoahTheLegend** [comment]
it is impossible to track if you got disconnected or quitted on purpose, neither there is a scripting way to check if bad deltas happened

**Comment by mugg91** [comment]
Thanks for dealing with these old issues lol.
Some of these are just random one-time occurences...
