### ISSUE TITLE
Bug: Ace of Spades glitch

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#11]
1. Have the perk Ace of Spades selected.
2. The game shows seemingly unintentional behavior when your inventory is full and you try to exchange items for Ace of Spades in your inventory.

For example, you can exchange missiles (an 2x2 item) with Ace of Spades which will result in getting rid of Ace of Spades. At this point one of two things could happen.

1) Ace of Spades will be added back to your inventory as soon as an empty 1x1 spot becomes available. 
2) An 1x1 spot in your inventory will be seemingly empty but cannot be occupied or exchanged.

Instead of being able to click on Ace of Spades to remove it from your inventory, the game should not even process the removal.
Perhaps it is also possible to initialize the player's inventory to have 1 spot less to begin with.

**Comment by NoahTheLegend** [comment]
fixed

**Comment by mugg91** [comment]
Not fixed and can still be put in other inventories.

**Comment by mugg91** [comment]
You can out an Ace from another inventory into yours.
Ace of spades will take effect (save you from death) even when you have a different perk selected.
