### ISSUE TITLE
"Cheaper molotov" perk is a lie

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#115]
Was playing in tickets mode on map "Taiga" 
My team had the "cheapter molotov" perk.
https://i.imgur.com/Yqqjp8q.png

When buying molotovs, it would say it costs 10 but I couldn't click the buy button until I had 15 coins, depleting all 15 coins when clicking it.

**Comment by NoahTheLegend** [comment]
what map was it?

**Comment by NoahTheLegend** [comment]
"cheaper molotovs" means they are cheaper in munitions shop (and some other structures) as item on its own but only for corresponding team. If show wasnt purple-colored, it is rather a map issue
