### ISSUE TITLE
Boombox lags everyone while switching music if there are many people on server

### ISSUE THREAD

**Issue by NoahTheLegend** [NoahTheLegend/kaww#124]
It is most likely related to incorrect commands system. Apparently because a command is sent from __each__ client to server, duplicating it multiple times, then server is sending a callback to each client N amount of times. Where N is amount of players sent the command to server.
Related to recent changes made by @mugg91 
https://github.com/NoahTheLegend/kaww/pull/122

**Comment by mugg91** [comment]
I'll look into it.

**Comment by mugg91** [comment]
Did you test it? Is it working?
@NoahTheLegend
