### ISSUE TITLE
"Blue" and "Red" texts on maps

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#133]
Some maps have castle back tiles aligned so they read Blue and Red.
But it doesn't make sense since teams can now be any color.
I suggest to remove these castle back tiles.
Maybe add in a blob instead, just a large team-colored sign that says "RED TEAM", "ORANGE TEAM", "GREEN TEAM", "BLUE TEAM", "BLACK TEAM" etc.
The sign could be possible to damage and destroy.

**Comment by NoahTheLegend** [comment]
these patterns have been decorative are outdated and it takes a while to spot every single map containing them. I will solve it eventually
