### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#135]
While browsing recent updates, I found these errors:

* in `TipsAndMessagesSpam.as`
`"Did you know? There are tens of built-in custom music tracks. Enable in-game musing through your settings"`
Should it be "Enable in-game music" ?

* in `MunitionsShop.as`
`Standard issue millitary helmet, blocks a small amount of bullet damage, occasionally blocks bullets.!`
The sentence should end either with a . or with a !

**Comment by NoahTheLegend** [comment]
thank you
