### ISSUE TITLE
F1 help shows gibberish in the top of the screen

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#138]
Pressing F1 to show help with display some grey blocks/buttons at the top of the screen. It doesn't seem to have any purpose.

**Comment by mugg91** [comment]
Maybe you can show the colorblindness settings on the F1 screen so it doesn't have to be a button that is on screen all the time, in order to fix https://github.com/NoahTheLegend/kaww/issues/136

**Comment by NoahTheLegend** [comment]
the buttons in top right screen are supposed for people who can't see them in tab menu, and settings menu will get filled with different options and preferences with time. Visual button for settings menu is also a pinpointer for people with "tunnel vision"
