### ISSUE TITLE
Bug: Antitank Missile went through 1 block tall ceiling

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#18]
Had this happen once. Not sure if this is a common thing.

1. Aim at a 1 block-tall row of blocks above you.
2. Shoot.
3. Notice the missile went through.

**Comment by NoahTheLegend** [comment]
Thats either intended behavior with penetrative properties of a shell, or was decided to leave it so (raycasts explode shell before it reachs the wall so explosion becomes weaker).
Although it is possible to make destrottile() on raycast when a shell incomes, so penetrative effect would be shown up properly
