### ISSUE TITLE
Bug: Hitting a blob with shovel will also destroy background

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#19]
1. Switch to shotgunner class.
2. Stand at a stone background.
3. Stand inside sandsacks, bunker, crate, ammo material (anything that is a blob)
4. Use shovel to try to destroy the blob.
5. Notice that you will destroy background. It will not happen if there is no blob.

Can be used to collapse buildings easily.

**Comment by NoahTheLegend** [comment]
fixed
