### ISSUE TITLE
Bug: Invisible items in inventory

### ISSUE THREAD

**Issue by StalkerSKAT** [NoahTheLegend/kaww#22]
Sometimes, if you put something in inventory, item what you putted starting be invisible. If you change class, item is visible again
Also you can't take invisible item from inventory (Because is not existing for you)

not depending on any special situation (I guess)
found with Javelins and Heat warheads

**Comment by StalkerSKAT** [comment]
I think is fixable by adding inventory sync or refresh rate (Like every 1 min)

**Comment by NoahTheLegend** [comment]
inventory is hardcoded, can't sync it at any way, sorry

**Comment by mugg91** [comment]
I've seen all sorts of weird inventory bugs because of missiles (that take up 2x2 spaces unlike other items).
