### ISSUE TITLE
Bug: Tickets gamemode: if entire team killed is count like defeat

### ISSUE THREAD

**Issue by StalkerSKAT** [NoahTheLegend/kaww#29]
Title and yea even if team have tickets

**Comment by mugg91** [comment]
Blue team has 90 tickets left, red team has no tickets left.
All players of blue team die, red team wins.
In match with few players, this could possibly happen and seems like a bad thing.

**Comment by mugg91** [comment]
It happens only sometimes. Also saw it happen in "destroy the truck" game mode.
