### ISSUE TITLE
Bug: Civilian car triggers friendly land mine

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#30]
Not confirmed but I'm almost sure that's happening.

1. Drive in a civilian car and move across one of your land mines
2. Land mine explodes

**Comment by StalkerSKAT** [comment]
Maybe is because is enemy civ car? Just because there are no capturing for civ cars, you can use enemy cars

**Comment by mugg91** [comment]
It also collides with and destroys friendly doors.
