### ISSUE TITLE
Bug: Driving vehicles out of map will cause out of bounds glitches

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#39]
Driving truck or flying a plane against the side of the map (black area) will cause bugs to happen such as

- Falling down with your vehicle. The vehicle will teleport back to the side of the map but you will sometimes die from falling offscreen.
- Plane will zip back and forth, sometimes plane explodes.

**Comment by NoahTheLegend** [comment]
it probably collides with something, not sure how to reproduce it so im closing it. Just do not pilot ur aircraft out of bounds
