### ISSUE TITLE
Bug: Can't place spiked wire on stone background

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#44]
Can't seem to place spiked wire on stone background. But anywhere else it works.
EDIT: There are apparently more places where the game says you could place a wire, but it actually doesn't let you, such as next to ladders.

**Comment by NoahTheLegend** [comment]
its said in the description, that it can be put only next to solid blocks

**Comment by mugg91** [comment]
I'm just saying game should show it in red color that thing can't be placed there.
