### ISSUE TITLE
Feature: refund 1 ticket to your team if going spectator right after spawning

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#45]
1. Die
2. Respawn - depletes one ticket
3. Go spectator
4. You wasted one ticket.

This is a suggestion that after step 3, the game refunds 1 ticket to your team.
You could add logic to check if you moved, did something significant, or if 5 seconds passed, etc.

**Comment by mugg91** [comment]
Although this is marked as completed, it's not happening ingame.
I go spectator as soon as I spawn without moving and ticket is not being refunded.

**Comment by NoahTheLegend** [comment]
should be done since 4.7 i think

**Comment by mugg91** [comment]
Have not checked this in a long time. If I see something strange I will post here again.
