### ISSUE TITLE
Change: Builder should be able to destroy outpost faster

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#47]
I tried to destroy my outpost in order to change location to somewhere else.
But it seems to take forever to do it.
Builder can pickaxe enemy tank to deal good damage, so why not deal good damage to wooden structures like outpost?

**Comment by NoahTheLegend** [comment]
its intentional thing, to prevent accident hitting. Making a special feature that allows to break it faster\slower (such as hitting with held DOWN button) would change it to be much less intuitive
