### ISSUE TITLE
Bug: AntiTank firing two missiles at once

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#48]
Reporting this bug I saw someone do.
They didn't reply to me how they do it, but they were reloading, then could fire twice in quick succession, reload again etc.
Both missile shots destroyed stuff separately so it wasn't just graphical.

I know archer bot in vanilla KAG has a bug that lets them shoot two arrows in quick succession, not sure if related.
Not sure if it was a bot or if there are AntiTank bots.

**Comment by StalkerSKAT** [comment]
Already known
