### ISSUE TITLE
Bug: Player gets launched to the sky when unmounting Bike

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#5]
1. Drive the bike (backseat or front seat)
2. Have the bike bounce around on the ground for a while.
3. Unmount.
4. At a low chance, you can get launched to the sky at very high speed.

When I have video available, I will update this post.

**Comment by NoahTheLegend** [comment]
funi

**Comment by mugg91** [comment]
Why it's not getting fixed?

**Comment by mugg91** [comment]
Still happening and costing me games.
Situations like this are common and ruin my fun:
I buy 6 missiles, 2 grenades, go to the battle and mount a machine gun from tank to shoot like 2 times then unmount.
Suddenly I fly up and fall down and die, enemy takes all my stuff, takes flag and wins.

Please reconsider about fixing this game-breaker bug.

**Comment by mugg91** [comment]
I haven't seen this at all in the last 10 days, so I guess it is fixed now?
