### ISSUE TITLE
Bug: Some mountable things don't say when the "engines start"

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#52]
For example, the "Heavy Machine gun" will not shoot until 1 min passed, but doesn't indicate this with any text.
I think same for Barge.

**Comment by mugg91** [comment]
On the small map, heavy machine gun cannot be used until 1 minute passes. 
It doesn't indicate this by any text.
Since enemy player will arrive before 1 minute passes, this is a problem.

It should be possible to use it earlier.
The wait time should possibly be removed from the small maps.

**Comment by NoahTheLegend** [comment]
insignificant
