### ISSUE TITLE
Change Request: Selected Perk should be saved

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#6]
1. Play the game.
2. Select a perk.
3. Disconnect and play again later.
4. Notice that you have no perk selected.

This is a request that the perk should be saved and reloaded along with your other player data (such as points earned).

**Comment by NoahTheLegend** [comment]
It is saved? Probably server restarted after yours reconnect

**Comment by NoahTheLegend** [comment]
Its unnecessary, wont do, sry
