### ISSUE TITLE
Bug: Planes zip downwards when flying too high

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#60]
If your plane flies too high, it will be moved a few pixels downwards suddenly.

This causes misjudgement. 
Player thinks he can pass a tower, but then he gets placed right in front of the wall and plane explodes.

The plane should be kept at same altitude when flying too high.

**Comment by NoahTheLegend** [comment]
afaik it is strictly bound to shape update frequency and how controlling a blob via attachment point works. Not worth fixing, as it involves more engine \ physics changes rather than mod
