### ISSUE TITLE
Bug: Automatic turrets don't shoot through sideward platforms

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#65]
https://imgur.com/oz5PYrI.png
Sorry, I don't have a better screenshot.
I think there is blue player shooting from a heavy machine gun.
Either way, the automatic turret in the same location isn't shooting because of the sidewards platforms (that's the bug I'm reporting).

Might apply to organic turret, too.

**Comment by NoahTheLegend** [comment]
done
