### ISSUE TITLE
Bug: When placing Spiked Wire, the Spiked Wire vanishes

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#67]
1. Be builder
2. Select spiked wire.
3. Place a bunch of spiked wire.
4. Notice sometimes the spiked wire will disappear (i.e. it will be unselected from your hand).

The cause of this bug is not known yet.

**Comment by NoahTheLegend** [comment]
as i had noticed the cause of bug was lacking a check for custom tiles nearby, for now barbed wire can be placed only nearby solid tiles
