### ISSUE TITLE
Bug: Massive sprites and server crash

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#68]
This kind of bug happens from time to time.
Huge sprite covers your screen.
Sometimes it's happening for a short time and the game recovers, sometimes it keeps the server stuck and it crashes.

I think this time I might be onto the cause of it...
I was builder with ace of spades perk.
My inventory was full. I tried exchanging an item for the Ace of Spades. (Bug described in [issue #11](https://github.com/NoahTheLegend/kaww/issues/11))
So I didn't have the ace in inventory anymore.
The game tried to insert it back into my inventory over and over, indicated by brief repeated sprite appearances on my character.
I fell a tree and chucked wood, then suddenly lots of aces of spades dropped on the floor, then there was a massive brown sprite on screen suddenly. The server froze and I had to close my game.

So I'm saying from these observations it might be linked to Ace of Spades.

**Comment by mugg91** [comment]
Since version 4, I had one situation where I picked something up and the game lagged to smithereens and I had to rejoin the server. Other than that, this issue seems to have become rare (?)

**Comment by NoahTheLegend** [comment]
this type of crash is fixed for now (i believe), the cause was occasionally colliding \ moving blobs with 0 or < 1 mass
