### ISSUE TITLE
Re-review bug reports that have been marked as fixed but aren't

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#69]
These issues are marked as completed but are still present in the game.

[Issue #7 - Bug: Spawn Immunity doesn't work with bullets and fire](https://github.com/NoahTheLegend/kaww/issues/7)
You don't take damage from mine, bullets and spiked wire, but you still get affected and take damage from fire.

[Issue #11 - Bug: Ace of Spades glitch](https://github.com/NoahTheLegend/kaww/issues/11)
You can still exchange other item for Ace of Spades in order to get rid of it. 
You can still place it in other inventories.
There is still a bug with being unable to place item in your inventory even though your space seems empty & items being in your inventory but not showing up in your inventory.
There is still a bug with placing an Ace of Spades from another inventory into yours in order to have it protect you from death even when you have a different perk selected.

[Issue #21 - Bug: Suicide will reduce hp to 1 when you have Ace of Spades](https://github.com/NoahTheLegend/kaww/issues/21)
Using Suicide from menu still reduces to 1 hp first.

[Issue #22 - Bug: Invisible items in inventory](https://github.com/NoahTheLegend/kaww/issues/22)
Seems linked to issue #11.

[Issue #40 - Bug: Stun bug with plane](https://github.com/NoahTheLegend/kaww/issues/40)
Still happens on the backup server which is said to use the latest code.

[Issue #45 - Feature: refund 1 ticket to your team if going spectator right after spawning](https://github.com/NoahTheLegend/kaww/issues/45)
When spawning and then going spectator right after, it will not refund a ticket.

**Comment by mugg91** [comment]
[Issue #70 - Change: Don't deplete a use from Wrench if it didn't actually repair anything](https://github.com/NoahTheLegend/kaww/issues/70)
It will still deplete use from Wrench even when the blob has full hp. 
The "fix" just made it so it doesn't activate when no eligible blob is nearby.

**Comment by NoahTheLegend** [comment]
> [Issue #70 - Change: Don't deplete a use from Wrench if it didn't actually repair anything](https://github.com/NoahTheLegend/kaww/issues/70) It will still deplete use from Wrench even when the blob has full hp. The "fix" just made it so it doesn't activate when no eligible blob is nearby.

^ fixed in https://github.com/NoahTheLegend/kaww/commit/0eb7c74f4e8cd1523d502f207c265904db2b32ed

> [Issue #76 - Bug: Ghillie Suit bush color is wrong on desert map ](https://github.com/NoahTheLegend/kaww/issues/76) Mechanic class with bush perk will still show up with wrong bush color on desert map.

^ fixed in https://github.com/NoahTheLegend/kaww/commit/8ad52e9bad3dafac6878414eef3b8998513b3898

**Comment by NoahTheLegend** [comment]
> [Issue #88 - Bug: Your Gate vanishes](https://github.com/NoahTheLegend/kaww/issues/88) The issue was last seen on **version 4.1** On a rare chance, after building a large door it will vanish.

^ will investigate, personally never encountered this after 4.0, and happened only once in ~3.? version

> [Issue #91 - Bug: When using stairs buttons, you will shoot](https://github.com/NoahTheLegend/kaww/issues/91) The issue was last seen on **version 4.2**

^ commented an explanation why it is not planned here. Did not mean to close as completed https://github.com/NoahTheLegend/kaww/issues/91#issuecomment-1947571525

**Comment by NoahTheLegend** [comment]
closing this one as i went through all cases you mentioned
