### ISSUE TITLE
Bug: Spawn Immunity doesn't work with bullets and fire

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#7]
1. Spawn at your base.
2. Get hit by bullets / fire / possibly many other damage sources.
3. Notice you take damage although you are still blinking white.

When blinking white, you should not take any damage.

**Comment by NoahTheLegend** [comment]
Engine issue. The problem is in SpawnImmunity.as, the check for ```victim is attacker``` passes for fire (didnt test with bullets). If i remove it, then hardcoded suicide button will allow you to fly.
