### ISSUE TITLE
Change: Don't deplete a use from Wrench if it didn't actually repair anything

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#70]
Using Wrench near a structure or vehicle will spawn stone particles as to indicate it was used.
After 100 uses the Wrench vanishes, even when it didn't actually repair something.
This is a suggestion to change Wrench so that stone particles are spawned and a use is depleted only when HP has actually been restored in a vehicle or structure.

**Comment by NoahTheLegend** [comment]
done

**Comment by mugg91** [comment]
Now it just activates when overlapping with a repairable structure or vehicle.
It still depletes uses even when the structure or vehicle is full hp.
