### ISSUE TITLE
Bug: Heavy Machine Gun wall clip

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#77]
https://imgur.com/ZFLrA39.png

**Comment by mugg91** [comment]
It also fits through 1 tile open gaps through the ground.
Although difficult to do, you could throw it up, mount it while it falls down through the gap and then unmount in order to pass through the gap.

**Comment by NoahTheLegend** [comment]
i dont mind that, the shape is that thin to prevent overlapping gunner's shape
