### ISSUE TITLE
Minor Bug: Helmet has different property depending how it was spawned

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#78]
This is a note that Helmet created by these two different means have different properties, which maybe should be looked into for concistency reasons.

### If you shoot with a Heavy Machine Gun on a Helmet bought from store or created from scrap at a truck:
- Absorbs bullets but doesn't get destroyed and doesn't produce stone particles and noise.

### If you shoot with a Heavy Machine Gun on a Helmet dropped from a Loot Box:
- Produces Stone particles and noise and gets destroyed after a few shots
- Can be made to not take damage if you place it in your head slot and then back on the ground.

**Comment by NoahTheLegend** [comment]
i think it is related to Shop script tagging materials invincible, ill get through it later
