### ISSUE TITLE
KAWW 3.0 - Change: Team color is not distinctive enough

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#90]
https://i.imgur.com/L1oDzxk.png

The blue colors look too similar so it is hard to distinguish who is friend or enemy.
May need to be addressed in the vanilla game.

**Comment by mugg91** [comment]
As pointed out by skemonde in discord, you can change TeamColors.png in a mod, so it doesn't have to be addressed in vanilla first.

**Comment by NoahTheLegend** [comment]
the issue is in that there are no much more different colors, and black\white look very weird, that means we reached the limit of different colors and i think we should keep it vanilla-ish
