### ISSUE TITLE
Change: Perk marker above player should be invisible when hiding in bush or behind wood logs

### ISSUE THREAD

**Issue by mugg91** [NoahTheLegend/kaww#93]
I don't think this is implemented, so I'm starting this issue.

When you are hiding behind scenery or items, your perk marker is still above your head, giving away your location to the enemy.

You could make it so it is hidden when the player is crouching or overlapping with a bush.

**Comment by NoahTheLegend** [comment]
hard to make it disappearing and appearing fancy, not a big deal, just use camouflage perk
